# Generated by Django 5.1.7 on 2025-03-14 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compartiment', '0001_initial'),
        ('etagere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_precise', models.CharField(max_length=30)),
                ('disponibilite', models.BooleanField(default=False)),
                ('id_compartiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compartiment.compartiment')),
                ('id_etagere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etagere.etagere')),
            ],
        ),
    ]
