# Generated by Django 5.1.7 on 2025-03-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auteur', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auteur',
            old_name='Nom',
            new_name='nom',
        ),
    ]
