# Generated by Django 5.1.7 on 2025-03-13 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etagere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compartiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nombreLivre', models.IntegerField()),
                ('domaineLivre', models.CharField(default='francais', max_length=255)),
                ('etagere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etagere.etagere')),
            ],
        ),
    ]
