# Generated by Django 5.1.7 on 2025-03-13 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auteur', '0001_initial'),
        ('product', '0006_alter_product_description_alter_product_ecrivain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auteur.auteur'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='static/images'),
        ),
    ]
