# Generated by Django 5.1.7 on 2025-04-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliothecaire',
            name='telephone',
            field=models.FloatField(max_length=20),
        ),
    ]
