# Generated by Django 5.1.7 on 2025-04-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaires', '0002_alter_bibliothecaire_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliothecaire',
            name='telephone',
            field=models.CharField(max_length=25),
        ),
    ]
