# Generated by Django 5.1.7 on 2025-04-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_librarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_publisher',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
