# Generated by Django 5.1.7 on 2025-03-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etagere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('etat_etagere', models.CharField(max_length=50)),
                ('mobilite', models.BooleanField(default=False)),
                ('charge_maximal', models.PositiveIntegerField()),
            ],
        ),
    ]
