# Generated by Django 5.1.7 on 2025-03-14 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auteur', '0001_initial'),
        ('compartiment', '0001_initial'),
        ('emplacement', '0001_initial'),
        ('etagere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('langueLivre', models.CharField(choices=[('FR', 'Français'), ('EN', 'Anglais'), ('ES', 'Espagnol'), ('DE', 'Allemand')], max_length=2)),
                ('annee_publication', models.PositiveIntegerField()),
                ('imagelivre', models.ImageField(default='path/to/default/image.jpg', upload_to='images/')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auteur.auteur')),
                ('compartiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compartiment.compartiment')),
                ('etagere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etagere.etagere')),
                ('id_emplacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emplacement.emplacement')),
            ],
        ),
    ]
