# Generated by Django 5.1.7 on 2025-03-20 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auteurs', '0001_initial'),
        ('livre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auteurs.auteurs'),
        ),
    ]
