# Generated by Django 5.1.7 on 2025-05-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='imagelivre',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
