# Generated by Django 5.1.7 on 2025-04-13 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abonnement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='date_debut',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='date_fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='prix',
            field=models.FloatField(default=15000, max_length=30),
        ),
    ]
