# Generated by Django 5.1.7 on 2025-04-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codecampus', models.CharField(max_length=50)),
                ('campus', models.CharField(max_length=50)),
            ],
        ),
    ]
