# Generated by Django 5.1.7 on 2025-04-11 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculte', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Niveaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('BAC1', 'Baccalaureat 1'), ('BAC2', 'Baccalaureat 2'), ('BAC3', 'Baccalaureat 3'), ('1Annee', 'Institut 1'), ('2Annee', 'Institut 2'), ('3Annee', 'Institut 3')], max_length=7)),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='universite.faculte')),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(max_length=33)),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='universite.faculte')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='universite.niveaux')),
            ],
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universite', models.CharField(max_length=33)),
                ('email_universite', models.EmailField(max_length=33)),
                ('site_web', models.URLField(max_length=33)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campus.campus')),
            ],
        ),
        migrations.AddField(
            model_name='faculte',
            name='universite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='universite.universite'),
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=33)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='universite.pays')),
            ],
        ),
        migrations.AddField(
            model_name='universite',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='universite.ville'),
        ),
    ]
