# Generated by Django 5.1.7 on 2025-04-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculte',
            name='faculte',
            field=models.CharField(max_length=33),
        ),
    ]
