# Generated by Django 5.1.7 on 2025-04-13 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('universite', '0002_alter_faculte_faculte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='faculte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universite.faculte'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universite.niveaux'),
        ),
        migrations.AlterField(
            model_name='faculte',
            name='universite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universite.universite'),
        ),
        migrations.AlterField(
            model_name='niveaux',
            name='faculte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universite.faculte'),
        ),
        migrations.AlterField(
            model_name='universite',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.campus'),
        ),
        migrations.AlterField(
            model_name='universite',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universite.ville'),
        ),
        migrations.AlterField(
            model_name='ville',
            name='pays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universite.pays'),
        ),
    ]
