# Generated by Django 5.1.7 on 2025-04-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0003_alter_departement_faculte_alter_departement_niveau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universite',
            name='universite',
            field=models.CharField(max_length=333),
        ),
    ]
