# Generated by Django 5.1.7 on 2025-04-09 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculte', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(max_length=50)),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='universites.faculte')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=50)),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='universites.departement')),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='universites.faculte')),
            ],
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universite', models.CharField(max_length=50)),
                ('pays', models.CharField(choices=[('DZ', 'Algérie'), ('AO', 'Angola'), ('BJ', 'Bénin'), ('BW', 'Botswana'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('CM', 'Cameroun'), ('CV', 'Cap-Vert'), ('CF', 'République Centrafricaine'), ('TD', 'Tchad'), ('KM', 'Comores'), ('CG', 'Congo-Brazzaville'), ('CD', 'Congo-Kinshasa'), ('DJ', 'Djibouti'), ('EG', 'Égypte'), ('GQ', 'Guinée équatoriale'), ('ER', 'Érythrée'), ('SZ', 'Eswatini'), ('ET', 'Éthiopie'), ('GA', 'Gabon'), ('GM', 'Gambie'), ('GH', 'Ghana'), ('GN', 'Guinée'), ('GW', 'Guinée-Bissau'), ('KE', 'Kenya'), ('LS', 'Lesotho'), ('LR', 'Liberia'), ('LY', 'Libye'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('ML', 'Mali'), ('MR', 'Mauritanie'), ('MU', 'Maurice'), ('MA', 'Maroc'), ('MZ', 'Mozambique'), ('NA', 'Namibie'), ('NE', 'Niger'), ('NG', 'Nigéria'), ('RW', 'Rwanda'), ('ST', 'Sao Tomé-et-Principe'), ('SN', 'Sénégal'), ('SC', 'Seychelles'), ('SL', 'Sierra Leone'), ('SO', 'Somalie'), ('ZA', 'Afrique du Sud'), ('SS', 'Soudan du Sud'), ('SD', 'Soudan'), ('TZ', 'Tanzanie'), ('TG', 'Togo'), ('TN', 'Tunisie'), ('UG', 'Ouganda'), ('ZM', 'Zambie'), ('ZW', 'Zimbabwe')], max_length=59)),
                ('ville', models.CharField(choices=[('ALGIERS', 'Alger'), ('CARTAGE', 'Carthage'), ('LAGOS', 'Lagos'), ('NAIROBI', 'Nairobi'), ('CAIRO', 'Le Caire'), ('DAKAR', 'Dakar'), ('ADDIS_ABABA', 'Addis-Abeba'), ('KAMPALA', 'Kampala'), ('TUNIS', 'Tunis'), ('HARARE', 'Harare'), ('ACCRA', 'Accra'), ('KIGALI', 'Kigali'), ('BAMAKO', 'Bamako'), ('LUANDA', 'Luanda'), ('BANGUI', 'Bangui'), ('BUJA', 'BUJUMBURA'), ('ANTANANARIVO', 'Antananarivo'), ('PORTO_NOVO', 'Porto-Novo'), ('BRAZZAVILLE', 'Brazzaville'), ('KINSHASA', 'Kinshasa'), ('FREETOWN', 'Freetown'), ('MONROVIA', 'Monrovia'), ('MASERU', 'Maseru'), ('MBABANE', 'Mbabane'), ('GABORONE', 'Gaborone'), ('MAPUTO', 'Maputo'), ('NOUAKCHOTT', 'Nouakchott'), ('NIAMEY', 'Niamey'), ('DJIBOUTI', 'Djibouti'), ('BISSAU', 'Bissau'), ('TANANARIVE', 'Tananarive'), ('LILONGWE', 'Lilongwe'), ('KAMPALA', 'Kampala'), ('HARARE', 'Harare'), ('BLOEMFONTEIN', 'Bloemfontein'), ('PRETORIA', 'Pretoria'), ('CAPE_TOWN', 'Le Cap')], max_length=50)),
                ('email', models.EmailField(max_length=20)),
                ('site_web', models.URLField(max_length=30)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campus.campus')),
            ],
        ),
        migrations.AddField(
            model_name='faculte',
            name='universite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='universites.universite'),
        ),
    ]
