# Generated by Django 5.1.7 on 2025-03-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteurs',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('postnom', models.CharField(max_length=30)),
                ('CNI', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
            ],
        ),
    ]
