# Generated by Django 5.1.7 on 2025-04-12 12:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livre', '0003_user'),
        ('universite', '0002_alter_faculte_faculte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=222)),
                ('prenom', models.CharField(max_length=222)),
                ('genre', models.CharField(choices=[('F', 'Feminin'), ('M', 'Masculin'), ('Au', 'Autres')], max_length=2)),
                ('matricule', models.CharField(max_length=220)),
                ('domicile', models.CharField(max_length=300)),
                ('date_emprunt', models.DateField(default=datetime.date.today)),
                ('date_fin_emprunt', models.DateField(null=True)),
                ('rendu', models.BooleanField(default=False)),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='universite.departement')),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='universite.faculte')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livre.livre')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='universite.niveaux')),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='universite.universite')),
            ],
        ),
    ]
