# Generated by Django 5.1.7 on 2025-04-13 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
        ('livre', '0003_user'),
        ('universite', '0002_alter_faculte_faculte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiants',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='universite.departement'),
        ),
        migrations.AlterField(
            model_name='etudiants',
            name='faculte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universite.faculte'),
        ),
        migrations.AlterField(
            model_name='etudiants',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livre.livre'),
        ),
        migrations.AlterField(
            model_name='etudiants',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universite.niveaux'),
        ),
        migrations.AlterField(
            model_name='etudiants',
            name='universite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universite.universite'),
        ),
    ]
